// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ConfirmedOwner$Type } from "./ConfirmedOwner";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ConfirmedOwner"]: ConfirmedOwner$Type;
    ["contracts/VRFCoordinatorMock/shared/access/ConfirmedOwner.sol:ConfirmedOwner"]: ConfirmedOwner$Type;
  }

  interface ContractTypesMap {
    ["ConfirmedOwner"]: GetContractReturnType<ConfirmedOwner$Type["abi"]>;
    ["contracts/VRFCoordinatorMock/shared/access/ConfirmedOwner.sol:ConfirmedOwner"]: GetContractReturnType<ConfirmedOwner$Type["abi"]>;
  }
}
