// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SubscriptionAPI$Type } from "./SubscriptionAPI";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SubscriptionAPI"]: SubscriptionAPI$Type;
    ["contracts/VRFCoordinatorMock/SubscriptionAPI.sol:SubscriptionAPI"]: SubscriptionAPI$Type;
  }

  interface ContractTypesMap {
    ["SubscriptionAPI"]: GetContractReturnType<SubscriptionAPI$Type["abi"]>;
    ["contracts/VRFCoordinatorMock/SubscriptionAPI.sol:SubscriptionAPI"]: GetContractReturnType<SubscriptionAPI$Type["abi"]>;
  }
}
