// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Lottery$Type } from "./Lottery";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Lottery"]: Lottery$Type;
    ["contracts/Lottery.sol:Lottery"]: Lottery$Type;
  }

  interface ContractTypesMap {
    ["Lottery"]: GetContractReturnType<Lottery$Type["abi"]>;
    ["contracts/Lottery.sol:Lottery"]: GetContractReturnType<Lottery$Type["abi"]>;
  }
}
