// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { LinkTokenInterface$Type } from "./LinkTokenInterface";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LinkTokenInterface"]: LinkTokenInterface$Type;
    ["contracts/VRFCoordinatorMock/shared/interfaces/LinkTokenInterface.sol:LinkTokenInterface"]: LinkTokenInterface$Type;
  }

  interface ContractTypesMap {
    ["LinkTokenInterface"]: GetContractReturnType<LinkTokenInterface$Type["abi"]>;
    ["contracts/VRFCoordinatorMock/shared/interfaces/LinkTokenInterface.sol:LinkTokenInterface"]: GetContractReturnType<LinkTokenInterface$Type["abi"]>;
  }
}
