// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IVRFCoordinatorV2Plus$Type } from "./IVRFCoordinatorV2Plus";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IVRFCoordinatorV2Plus"]: IVRFCoordinatorV2Plus$Type;
    ["@chainlink/contracts/src/v0.8/vrf/dev/interfaces/IVRFCoordinatorV2Plus.sol:IVRFCoordinatorV2Plus"]: IVRFCoordinatorV2Plus$Type;
  }

  interface ContractTypesMap {
    ["IVRFCoordinatorV2Plus"]: GetContractReturnType<IVRFCoordinatorV2Plus$Type["abi"]>;
    ["@chainlink/contracts/src/v0.8/vrf/dev/interfaces/IVRFCoordinatorV2Plus.sol:IVRFCoordinatorV2Plus"]: GetContractReturnType<IVRFCoordinatorV2Plus$Type["abi"]>;
  }
}
