// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IVRFMigratableConsumerV2Plus$Type } from "./IVRFMigratableConsumerV2Plus";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IVRFMigratableConsumerV2Plus"]: IVRFMigratableConsumerV2Plus$Type;
    ["contracts/VRFCoordinatorMock/shared/interfaces/IVRFMigratableConsumerV2Plus.sol:IVRFMigratableConsumerV2Plus"]: IVRFMigratableConsumerV2Plus$Type;
  }

  interface ContractTypesMap {
    ["IVRFMigratableConsumerV2Plus"]: GetContractReturnType<IVRFMigratableConsumerV2Plus$Type["abi"]>;
    ["contracts/VRFCoordinatorMock/shared/interfaces/IVRFMigratableConsumerV2Plus.sol:IVRFMigratableConsumerV2Plus"]: GetContractReturnType<IVRFMigratableConsumerV2Plus$Type["abi"]>;
  }
}
