// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    VRFConsumerBaseV2Plus: never;
    ConfirmedOwner: never;
    ConfirmedOwnerWithProposal: never;
    IOwnable: never;
    IVRFCoordinatorV2Plus: never;
    IVRFMigratableConsumerV2Plus: never;
    IVRFSubscriptionV2Plus: never;
    VRFV2PlusClient: never;
  }

  interface ContractTypesMap {
    VRFConsumerBaseV2Plus: never;
    ConfirmedOwner: never;
    ConfirmedOwnerWithProposal: never;
    IOwnable: never;
    IVRFCoordinatorV2Plus: never;
    IVRFMigratableConsumerV2Plus: never;
    IVRFSubscriptionV2Plus: never;
    VRFV2PlusClient: never;
  }
}
