// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { VRFV2PlusClient$Type } from "./VRFV2PlusClient";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["VRFV2PlusClient"]: VRFV2PlusClient$Type;
    ["contracts/VRFCoordinatorMock/shared/libraries/VRFV2PlusClient.sol:VRFV2PlusClient"]: VRFV2PlusClient$Type;
  }

  interface ContractTypesMap {
    ["VRFV2PlusClient"]: GetContractReturnType<VRFV2PlusClient$Type["abi"]>;
    ["contracts/VRFCoordinatorMock/shared/libraries/VRFV2PlusClient.sol:VRFV2PlusClient"]: GetContractReturnType<VRFV2PlusClient$Type["abi"]>;
  }
}
