// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IERC677Receiver$Type } from "./IERC677Receiver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC677Receiver"]: IERC677Receiver$Type;
    ["contracts/VRFCoordinatorMock/shared/interfaces/IERC677Receiver.sol:IERC677Receiver"]: IERC677Receiver$Type;
  }

  interface ContractTypesMap {
    ["IERC677Receiver"]: GetContractReturnType<IERC677Receiver$Type["abi"]>;
    ["contracts/VRFCoordinatorMock/shared/interfaces/IERC677Receiver.sol:IERC677Receiver"]: GetContractReturnType<IERC677Receiver$Type["abi"]>;
  }
}
