// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { VRFConsumerBaseV2Plus$Type } from "./VRFConsumerBaseV2Plus";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["VRFConsumerBaseV2Plus"]: VRFConsumerBaseV2Plus$Type;
    ["@chainlink/contracts/src/v0.8/vrf/dev/VRFConsumerBaseV2Plus.sol:VRFConsumerBaseV2Plus"]: VRFConsumerBaseV2Plus$Type;
  }

  interface ContractTypesMap {
    ["VRFConsumerBaseV2Plus"]: GetContractReturnType<VRFConsumerBaseV2Plus$Type["abi"]>;
    ["@chainlink/contracts/src/v0.8/vrf/dev/VRFConsumerBaseV2Plus.sol:VRFConsumerBaseV2Plus"]: GetContractReturnType<VRFConsumerBaseV2Plus$Type["abi"]>;
  }
}
